model:
  base_learning_rate: 4.5e-04
  target: taming.models.vqgan_1D.VQModel1D
  params:
    embed_dim: 64
    n_embed: 128
    image_key: wav
    ckpt_path: drive/MyDrive/NNTI/logs/2023-03-14T20-59-11custom_transformer/checkpoints/last.ckpt
    ddconfig:
      double_z: false
      z_channels: 64
      resolution: 64
      in_channels: 1
      out_ch: 1
      ch: 32 # 32 => 3m param 128 => 30m param
      ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [ 32 ]
      dropout: 0.1


    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator1D
      params:
        perceptual_weight: 0 # skip the VGG model loss part
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 1000
        disc_weight: 0.8
        codebook_weight: 1.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 # has to be one because of variable input length => no stacking possible
    num_workers: 1
    train:
      target: taming.data.custom_dataset.TrainLoader
      params:
        path_wav: 1D-VQ_GAN/dataset/speech_data
        split: 1
        apply_transform: true
    validation:
      target: taming.data.custom_dataset.TestLoader
      params:
        path_wav: 1D-VQ_GAN/dataset/speech_data
        split: 0.8
        apply_transform: false
