model:
  base_learning_rate: 4.5e-06
  target: taming.models.vqgan_1D.VQModel1D
  params:
    embed_dim: 512
    n_embed: 1024
    image_key: wav
    ddconfig:
      double_z: False
      z_channels: 512
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [ 16 ]
      dropout: 0.2

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator1D
      params:
#        perceptual_weight: 0 # skip the VGG model loss part
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 10000
        disc_weight: 0.8
        codebook_weight: 1.0


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 # has to be one because of variable input length => no stacking possible
    num_workers: 1
    train:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: train
    validation:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: dev
    test:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: test