model:
  base_learning_rate: 4.5e-04
  target: taming.models.DaddyTransformer.DaddyTransformer
  params:
    cond_stage_key: wav
    transformer_config:
      target: taming.modules.transformer.mingpt.GPT
      params:
        vocab_size: 512
        block_size: 64
        n_layer: 4
        n_head: 16
        n_embd: 128
    first_stage_config:
      target: taming.models.vqgan_1D.VQModel1D
      params:
        embed_dim: 64
        n_embed: 128
        image_key: wav
        ckpt_path: drive/MyDrive/NNTI/logs/2023-03-14T20-59-11custom_transformer/checkpoints/last.ckpt
        ddconfig:
          double_z: false
          z_channels: 64
          resolution: 64
          in_channels: 1
          out_ch: 1
          ch: 32 # 32 => 3m param 128 => 30m param
          ch_mult: [ 1,1,2,2,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 3
          attn_resolutions: [ 32 ]
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.models.dummy_cond_stage.DummyCondStage
      params:
        conditional_key: objects_bbox

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 # has to be one because of variable input length => no stacking possible
    num_workers: 1
    train:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset/speech_data
        split: train
    validation:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset/speech_data
        split: dev
    test:
      target: taming.data.custom_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset/speech_data
        split: test
