data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1 # has to be one because of variable input length => no stacking possible
    num_workers: 1
    train:
      target: taming.data.custom_image_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: train
        speaker: theo
        augment: true
    validation:
      target: taming.data.custom_image_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: dev
#        speaker: theo
        augment: false
    test:
      target: taming.data.custom_image_dataset.DatasetLoader
      params:
        path_wav: 1D-VQ_GAN/dataset
        tsv_path: 1D-VQ_GAN/dataset/SDR_metadata.tsv
        split: test
#        speaker: theo
        augment: false
